#cloud-config
package_update: true
package_upgrade: true
groups:
  - docker
users:
  - default
  - name: dba
    gecos: DBA
    primary_group: dba
    groups: docker, users, admin
    sudo: 'ALL=(ALL) NOPASSWD:ALL'
    shell: /bin/bash
    ssh_authorized_keys:
      - ${ssh_pub_key1}
      - ${ssh_pub_key2}
packages:
  - nano
  - iputils-ping
runcmd:
  - curl -fsSL https://get.docker.com | sh
  - docker -v >> /etc/motd
  - docker compose version >> /etc/motd
  - curl -fsSL https://tailscale.com/install.sh | sh
  - tailscale up --authkey ${tailscale_key}
  - tailscale version >> /etc/motd
  - curl https://raw.githubusercontent.com/joaoAaf/infra-oci-terraform/refs/heads/main/scripts/docker-compose_vm-01.yml > /home/dba/docker-compose.yml
  - chown dba:dba /home/dba/docker-compose.yml
  - chmod 644 /home/dba/docker-compose.yml
  - docker compose -f /home/dba/docker-compose.yml up -d