#cloud-config
package_update: true
package_upgrade: true
groups:
  - docker
users:
  - default
  - name: dba
    gecos: DBA
    primary_group: dba
    groups: docker, users, admin
    sudo: 'ALL=(ALL) NOPASSWD:ALL'
    shell: /bin/bash
    ssh_authorized_keys:
      - ${ssh_pub_key1}
      - ${ssh_pub_key2}
timezone: ${timezone}
packages:
  - nano
  - iputils-ping
runcmd:
  - curl -fsSL https://get.docker.com | sh
  - docker -v >> /etc/motd
  - docker compose version >> /etc/motd
  - curl -fsSL https://tailscale.com/install.sh | sh
  - tailscale up --authkey ${tailscale_key} --advertise-routes=10.0.1.0/24
  - tailscale version >> /etc/motd
  - curl https://raw.githubusercontent.com/joaoAaf/infra-oci-terraform/refs/heads/feature-backup-db/scripts/docker-compose_vm-01.yml > /home/dba/docker-compose.yml
  - export PUID=$(id -u dba)
  - export PGID=$(id -g dba)
  - export TZ=${timezone}
  - export WEBDAV_USERNAME=${webdav_username}
  - export WEBDAV_PASSWORD=${webdav_password}
  - |
    cat <<-EOF > /home/dba/pgbackup.sh
    #!/bin/bash
    pg_dumpall -c -U postgres | gzip -9 > /pgbackup/dump_\$(date +%Y-%m-%d"_"%H_%M_%S).sql.gz
    EOF
  - groupadd -g 999 postgres
  - chown dba:dba /home/dba/docker-compose.yml
  - chown dba:postgres /home/dba/pgbackup.sh
  - chmod 660 /home/dba/*
  - chmod +x /home/dba/pgbackup.sh
  - docker compose -f /home/dba/docker-compose.yml up -d