#cloud-config
package_update: true
package_upgrade: true
groups:
  - docker
system_info:
  default_user:
    groups: [docker]
packages:
  - nano
  - git
runcmd:
  - curl -fsSL https://get.docker.com | sh
  - curl -fsSL https://tailscale.com/install.sh | sh
  - tailscale up --authkey ${tailscale_key}
  - docker -v >> /etc/motd
  - docker compose version >> /etc/motd
  - tailscale version >> /etc/motd