volumes:
  pgdata:
    name: pgdata
  pgbackup:
    name: pgbackup

networks:
  pgnet:
    name: pgnet
    driver: bridge
  webdav-net:
    name: webdav-net
    driver: bridge

services:
  postgresql:
    container_name: postgresql
    image: postgres:17
    user: postgres
    networks:
      - pgnet
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgbackup:/pgbackup
      - /home/dba/pgbackup.sh:/usr/local/bin/pgbackup.sh
    ports:
      - 5432:5432
    environment:
      - TZ=${TZ}
      - POSTGRES_PASSWORD=${PG_PASS}
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      # o período de carência durante o qual o Compose não considerará as falhas de verificação de saúde (padrão 0s).
      # No entanto, se a verificação de saúde for bem-sucedida, o recipiente será marcado como saudável e o período de carência termina cedo.
      start_period: 1m
      # start_interval : 5s # o período entre os exames de saúde durante o período de carência (padrão 5s ).
      interval: 5s # o período entre os exames de saúde (padrão 30s).
      # timeout: 30s # o tempo dado ao comando a ser concluído (padrão 30s).
      retries: 10 # o número de falhas consecutivas antes de ser considerado insalubre (padrão 3).
  webdav-server:
    container_name: webdav-server
    image: joaoaaf/nginx-webdav
    networks:
      - webdav-net
    volumes:
      - pgbackup:/var/www/dav
    ports:
      - 443:443
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBDAV_USERNAME=${WEBDAV_USERNAME}
      - WEBDAV_PASSWORD=${WEBDAV_PASSWORD}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-fk", "https://localhost/health"]
      start_period: 1m
      interval: 5s
      retries: 10  